..\..\..\..\..\..\src\app\read_blast_result\match.cpp(202) : error C2593: 'operator <<' is ambiguous ..\..\..\..\..\..\src\app\read_blast_result\missing.cpp(196) : error C2593: 'operator <<' is ambiguous ..\..\..\..\..\..\src\app\read_blast_result\missing.cpp(197) : error C2593: 'operator <<' is ambiguous ..\..\..\..\..\..\src\app\read_blast_result\read_trna.cpp(86) : error C2593: 'operator <<' is ambiguous
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@46693 78c7ea69-d796-4a43-9a09-de51944f1b03