CAlnError: add GetMsg(), deprecate GetMessage() - to avoid conflict w/ Windows macro.  JIRA:CXX-3868
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@57373 78c7ea69-d796-4a43-9a09-de51944f1b03