CCassandraException: Modernize override indications.
Use override rather than virtual (which was always redundant) for
consistency with NCBI_EXCEPTION_DEFAULT.  JIRA: ID-7622.

git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@99314 78c7ea69-d796-4a43-9a09-de51944f1b03